<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Convert_UI_Assets_BG3</AssemblyName>
    <ApplicationIcon>Lumox.ico</ApplicationIcon>
    <RootNamespace>DDS_Convert</RootNamespace>
    <Version>1.4.0</Version>
    <Product>BG3 DDS Convert</Product>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Include="lib\texconv.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\LICENSE-texconv.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>